"""phase2 devices pairing send jobs

Revision ID: 9bfd64b68082
Revises: c86a3a9d1076
Create Date: 2026-08-14 17:26:01.445912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9bfd64b68082'
down_revision: Union[str, None] = 'c86a3a9d1076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pairing_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=False),
    sa.Column('device_identifier', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pairing_sessions_token_hash'), 'pairing_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_pairing_sessions_user_id'), 'pairing_sessions', ['user_id'], unique=False)
    op.create_table('send_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('rate_per_minute', sa.Integer(), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_send_jobs_campaign_id'), 'send_jobs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_send_jobs_device_id'), 'send_jobs', ['device_id'], unique=False)
    op.create_index(op.f('ix_send_jobs_status'), 'send_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_send_jobs_user_id'), 'send_jobs', ['user_id'], unique=False)
    op.create_index('uq_sendjob_campaign', 'send_jobs', ['campaign_id'], unique=True)
    op.create_table('message_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_timestamp', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['campaign_recipients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attempt_campaign_status', 'message_attempts', ['campaign_id', 'status'], unique=False)
    op.create_index(op.f('ix_message_attempts_campaign_id'), 'message_attempts', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_message_attempts_contact_id'), 'message_attempts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_message_attempts_idempotency_key'), 'message_attempts', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_message_attempts_message_id'), 'message_attempts', ['message_id'], unique=True)
    op.create_index(op.f('ix_message_attempts_recipient_id'), 'message_attempts', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_message_attempts_status'), 'message_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_message_attempts_user_id'), 'message_attempts', ['user_id'], unique=False)
    op.create_index('uq_attempt_idempotency', 'message_attempts', ['idempotency_key'], unique=True)
    op.add_column('campaign_recipients', sa.Column('message_id', sa.String(length=64), nullable=True))
    op.add_column('campaign_recipients', sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaign_recipients', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaign_recipients', sa.Column('attempt_count', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_campaign_recipients_message_id'), 'campaign_recipients', ['message_id'], unique=False)
    op.add_column('devices', sa.Column('public_key', sa.Text(), nullable=True))
    op.add_column('devices', sa.Column('paired_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('devices', sa.Column('phone_model', sa.String(length=120), nullable=True))
    op.add_column('devices', sa.Column('android_version', sa.String(length=40), nullable=True))
    op.add_column('devices', sa.Column('app_version', sa.String(length=40), nullable=True))
    op.add_column('devices', sa.Column('battery_level', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('sim_state', sa.String(length=40), nullable=True))
    op.add_column('devices', sa.Column('network_state', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'network_state')
    op.drop_column('devices', 'sim_state')
    op.drop_column('devices', 'battery_level')
    op.drop_column('devices', 'app_version')
    op.drop_column('devices', 'android_version')
    op.drop_column('devices', 'phone_model')
    op.drop_column('devices', 'paired_at')
    op.drop_column('devices', 'public_key')
    op.drop_index(op.f('ix_campaign_recipients_message_id'), table_name='campaign_recipients')
    op.drop_column('campaign_recipients', 'attempt_count')
    op.drop_column('campaign_recipients', 'sent_at')
    op.drop_column('campaign_recipients', 'queued_at')
    op.drop_column('campaign_recipients', 'message_id')
    op.drop_index('uq_attempt_idempotency', table_name='message_attempts')
    op.drop_index(op.f('ix_message_attempts_user_id'), table_name='message_attempts')
    op.drop_index(op.f('ix_message_attempts_status'), table_name='message_attempts')
    op.drop_index(op.f('ix_message_attempts_recipient_id'), table_name='message_attempts')
    op.drop_index(op.f('ix_message_attempts_message_id'), table_name='message_attempts')
    op.drop_index(op.f('ix_message_attempts_idempotency_key'), table_name='message_attempts')
    op.drop_index(op.f('ix_message_attempts_contact_id'), table_name='message_attempts')
    op.drop_index(op.f('ix_message_attempts_campaign_id'), table_name='message_attempts')
    op.drop_index('ix_attempt_campaign_status', table_name='message_attempts')
    op.drop_table('message_attempts')
    op.drop_index('uq_sendjob_campaign', table_name='send_jobs')
    op.drop_index(op.f('ix_send_jobs_user_id'), table_name='send_jobs')
    op.drop_index(op.f('ix_send_jobs_status'), table_name='send_jobs')
    op.drop_index(op.f('ix_send_jobs_device_id'), table_name='send_jobs')
    op.drop_index(op.f('ix_send_jobs_campaign_id'), table_name='send_jobs')
    op.drop_table('send_jobs')
    op.drop_index(op.f('ix_pairing_sessions_user_id'), table_name='pairing_sessions')
    op.drop_index(op.f('ix_pairing_sessions_token_hash'), table_name='pairing_sessions')
    op.drop_table('pairing_sessions')
    # ### end Alembic commands ###
