package com.messageflow.app.data

import kotlinx.serialization.json.Json

/**
 * Parses the QR payload generated by the backend's
 * POST /api/devices/pairing/start: {"mf":1,"server":...,"token":...}.
 * Pure Kotlin so it is unit-testable on the JVM.
 */
object QrPayloadParser {

    fun parse(raw: String): Map<String, String> {
        val element = Json { ignoreUnknownKeys = true }
            .parseToJsonElement(raw).jsonObject
        return mapOf(
            "server" to (element["server"]?.toString()?.trim('"') ?: ""),
            "token" to (element["token"]?.toString()?.trim('"') ?: ""),
        )
    }
}
